from typing import Any, Union
import pandas as pd

class AverageTrueRange:
    def __init__(self, high: pd.Series, low: pd.Series, close: pd.Series, window: int = 14, fillna: bool = False) -> None: ...
    def average_true_range(self) -> pd.Series: ...

class RSIIndicator:
    def __init__(self, close: pd.Series, window: int = 14, fillna: bool = False) -> None: ...
    def rsi(self) -> pd.Series: ...

class ROCIndicator:
    def __init__(self, close: pd.Series, window: int = 12, fillna: bool = False) -> None: ...
    def roc(self) -> pd.Series: ...

class ADXIndicator:
    def __init__(self, high: pd.Series, low: pd.Series, close: pd.Series, window: int = 14, fillna: bool = False) -> None: ...
    def adx(self) -> pd.Series: ...

class OnBalanceVolumeIndicator:
    def __init__(self, close: pd.Series, volume: pd.Series, fillna: bool = False) -> None: ...
    def on_balance_volume(self) -> pd.Series: ... 